# Generated by Django 5.0.1 on 2024-01-22 21:02

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscan',
            name='age',
            field=models.IntegerField(default='2', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userscan',
            name='contactNumber',
            field=models.CharField(default='000', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userscan',
            name='email',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userscan',
            name='gender',
            field=models.CharField(default='male', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userscan',
            name='length',
            field=models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userscan',
            name='name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userscan',
            name='submitDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
