# Generated by Django 5.0.1 on 2024-01-25 16:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_systemconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscan',
            name='submitDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
